export const FETCH_PATIENTS = "FETCH_PATIENTS";
export const NEXT_PATIENTS = "NEXT_PATIENTS";
export const PREV_PATIENTS = "PREV_PATIENTS";
export const POPULATE_PATIENTS = "POPULATE_PATIENTS";
export const POPULATE_SEARCH_RESULTS = "POPULATE_SEARCH_RESULTS"
export const SEARCH_PATIENTS = "SEARCH_PATIENTS";
export const CLEAR_SEARCH_RESULTS = "CLEAR_SEARCH_RESULTS"
export const RESET_PATIENTS = "RESET_PATIENTS";

